name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/*/Chart.yaml"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          ref: main
          path: main

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          ref: gh-pages
          path: gh-pages

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.2

      - name: Add the repo itself to get dependencies
        run: helm repo add truefoundry "https://raw.githubusercontent.com/${{ github.repository }}/gh-pages" --username "${{ secrets.GITHUB_TOKEN }}" --password "${{ secrets.GITHUB_TOKEN }}"

      - name: Switch to main branch dir
        run: |
          echo "Switching to main and generating helm charts"
          cd main
          mkdir packages
          for dir in ./charts/*     
          do
            echo "Building ${dir}"
            helm dependency update ${dir}
          done
          helm package charts/* --destination packages

      - name: Move packaged helm charts to gh-pages branch if they don't exist already
        run: |
          cd gh-pages
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          mv -vn ../main/packages/* .
          git add *.tgz
          git status
          git diff-index --quiet HEAD || 
             (helm repo index . && 
             git commit -a -m '[CI] Publish charts' && 
             git push origin gh-pages)